version = 1

[[analyzers]]
name = "shell"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "javascript"

[[transformers]]
name = "black"

[[transformers]]
name = "isort"

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"
