FROM python:3.14@sha256:288157085f183c0000cb14cbf5c81d304f2dcdc4c386578a0c1bd214d178f7a4

# Set the working directory in the container
WORKDIR /build

# Copy the requirements file to the container
COPY requirements.txt .
COPY requirements-test.txt .

# Install the Python dependencies
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt \
    && pip install --no-cache-dir -r requirements-test.txt


