---
version: "3"
services:
  ngrok:
      image: ngrok/ngrok:latest
      restart: unless-stopped
      environment:
        - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      command:
        - "start"
        - "--all"
        - "--config"
        - "/etc/ngrok.yml"
      volumes:
        - ./ngrok.yml:/etc/ngrok.yml
      ports:
        - 4040:4040
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./runtime-nginx-config/:/config
      - ./nginx/site-confs/proxy-gate-backend.conf:/config/nginx/site-confs/proxy-gate-backend.conf:ro
      - ./nginx/site-confs/proxy-gate.conf:/config/nginx/site-confs/proxy-gate.conf:ro
      - ./nginx/site-confs/sample-plex-auth.conf:/config/nginx/site-confs/sample-plex-auth.conf:ro
      - ./nginx/site-confs/sample-google-auth.conf:/config/nginx/site-confs/sample-google-auth.conf:ro
      - ./nginx/www/protected-index.html:/config/www/protected-index.html:ro
    ports:
      - 80:80
      - 443:443
      - 8080:8080 # proxy gate accessible via nginx
    restart: unless-stopped

  proxy-gate:
    image: ghcr.io/digimach/proxy-gate:${BUILD_VERSION}
    volumes:
      - ./runtime-proxy-gate-data/:/data
    restart: unless-stopped
