name: Test the application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Run pytest
        run: |
          make pytest

